# Generated by Django 3.2 on 2021-04-12 07:15

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20210411_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentcompleted',
            old_name='date_completed',
            new_name='date_submited',
        ),
        migrations.AddField(
            model_name='assignmentcompleted',
            name='attachment',
            field=models.FileField(null=True, upload_to=assignments.models.attachment_upload_path),
        ),
        migrations.AddField(
            model_name='assignmentcompleted',
            name='more',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentcompleted',
            name='score',
            field=models.IntegerField(max_length=100),
        ),
    ]
