# Generated by Django 3.2 on 2021-04-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='class_name',
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.classroom'),
        ),
    ]
