# Generated by Django 3.2 on 2021-04-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_auto_20210412_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='owner_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.teacher'),
        ),
    ]
