# Generated by Django 3.2 on 2021-04-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_classroom_owner_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
