# Generated by Django 3.2 on 2021-04-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_alter_classroom_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='owner',
            new_name='owner_teacher',
        ),
    ]
