# Generated by Django 3.2 on 2021-04-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_rename_owner_assignment_owner_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcompleted',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
